First Pull Request for review
K0ppai/hello-microverse-project pull request #1
Opened 2023-04-25 15:09 UTC by K0ppai

2023-04-25 15:21 UTC, bienvenuushindi requested changes
### Hi @K0ppai ,

Good job implementing most of the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:

- All linters checks are ok. ✔


## (Changes Required) Aspects to improve: ♻️

- [ ] Please make sure Your README file looks great and professional. Kindly consider making it more descriptive by adding as many sections as possible from the [README template](https://github.com/microverseinc/readme-template) provided by Microverse and remember to customize it. 
![reademe](https://user-images.githubusercontent.com/26736582/234324175-a4cdf47d-7110-4cd9-9f32-a14115421146.png)

- [ ] Please make sure your Pull Request  has a summary describing the introduced changes in more detail.  As you can see there is no description provided for this PR
![prdescriptive](https://user-images.githubusercontent.com/26736582/234324712-05c198e5-0b02-4ef1-9c48-3419eb1026e9.png)


**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-26 09:12 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @K0ppai :wave: 

Well done on implementing the changes suggested by the previous reviewer. :+1:  
You need to fix those issues before moving to the next project. :running_man: 

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Linters checks are passing.
✔️ You have used the correct gitflow.
✔️ Commit message is professional

## Required Changes ♻️

- [ ] Though you have added a description in the pull request but still it is not professional. In the description you need to describe what you have done in the whole project, not in the last commit. Here I am giving you an example, Kindly consider this and fix the issue.

  - ***You can write in the pull request description:***
>     - In this project I have implemented the requirements below:
>       - Implement basic `CSS` and `HTML`.
>       - Implement `linters` and configure them with the project.
>       - Use `Microverse Readme` file and customize it.
>       - Create a `test.md` file and ignore it by using `.gitignore`.

    
![image](https://user-images.githubusercontent.com/60083437/234527340-57c5d8d9-0fff-440d-a42c-3c5b66e3855e.png)


> Kindly check the comments below.

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 12:18 UTC, Olamarx approved these changes
Hi @K0ppai, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif"/>
## Highlights
- Linters passed ✔️ 
- PR description ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 12:18 UTC, Olamarx commented on README.md
> +- [Live Demo Link](https://github.com/K0ppai/hello-microverse-project)
- [OPTIONAL] Since you have not deployed it, I strongly advise you to remove this.

2023-04-26 16:45 UTC, merged